### ISSUE TITLE
Ghost code and annotation

### ISSUE THREAD

**Issue by vprevosto** [acsl-language/acsl#3]
Is the usage of `/@  @/` to delimit multi-line annotations in ghost code the best way to handle, or should we stick to `/*@ ... */` event if that means nested comments for standard C compiler?

**Comment by davidcok** [comment]
Since ghost code is already in an annotation comment, does the specification for the ghost code need to be in an embedded comment?  Or would omitting such delimiters make problems for the parser?

**Comment by vprevosto** [comment]
Omitting the delimiters would indeed complicate things for the parser, as ACSL and C (ghost or not) syntaxes are quite different. Having delimiters makes it easy to know when to switch between the two.

In addition, the development version of Frama-C recently gained support for `/@ @/` in ghost code, making the issue rather moot.
