### ISSUE TITLE
@ symbols

### ISSUE THREAD

**Issue by davidcok** [acsl-language/acsl#34]
The introduction says that @ symbols in an annotation are equivalent to blanks.
But the section on ghost code says that @ symbols at the beginning of lines and end of the comment are blanks, which does not include all @ symbols.

Which is it to be?

**Comment by vprevosto** [comment]
The former: all `@` symbols in an ACSL annotations are considered as blanks.

**Comment by jensgerlach** [comment]
This might no be the best place to mention this but I this issue reminds me of an idea Loïc
told me about: If `x` is a variable (or lvalue?) and `L` a label, then instead of
`\at(x, L)` one is allowed to write `x@L`.

I think this looks neat!

**Comment by AllanBlanchard** [comment]
The formulation is clear : it is always blank, and we find them commonly at beginning/end.
