### ISSUE TITLE
Exact program state of Pre and Post states

### ISSUE THREAD

**Issue by vprevosto** [acsl-language/acsl#70]
ACSL manual states that (section 2.3.1)

> C function parameters are obtained by value from actual parameters that mostly remain
unaltered by the function calls. For that reason, formal parameters in function contracts
are defined such that they always refer implicitly to their values interpreted in the pre-state.

However, this leaves out some important questions, notably whether we can speak about the address of such formal parameters. Basically, given a function `rettype f(prms) { body; return r; }`, a call `lval = f(args)` can be decomposed as such (we assume that the body of `f` is normalized and there's a single `return` statement)

**EDIT** as mentioned in [a comment](https://github.com/acsl-language/acsl/issues/70#issuecomment-771033441) below, the initial `// Post` labels were incorrectly placed.

```diff
// Pre1 
{ 
   rettype retvar;
// Pre2
  { 
     prms = args;
// Pre3
    {
        body;
        retvar = r;
-// Post1
    }
+// Post1
-// Post2
  }
+//Post2
 lval = retvar;
-// Post3
 }
+//Post3
```

In this context, there are three places where the `Pre` (as in `\at(.,Pre)`) state of `f` could be located. `Pre2` is not really useful: it only give access to the location where the returned value will be temporarily placed, and by definition `retvar` is uninitialized until the `Post` state. Equating `Pre` with `Pre1` implies that we cannot take the address of the formals in the pre state, and notably that it is not possible to state something like `\initialized(&prm)`. Basically, the `requires` of `f` would be translated at `Pre1` as `assert R{prms <- args}` where `{prms <- args}` denotes the substitution of `prms` by `args`. Equating `Pre` with `Pre3` implies that we have addresses attached to the formals.

Similarly, equating `Post` with `Post1` implies that we can speak about the addresses of the formals, and of `retvar`. In particular, if `p` holds the address of a formal, `ensures \valid(p);` will be true. This is not the case if we equate `Post` with `Post2` or `Post3`, but in the former case it might be possible to refer to the adress of `\result` (so that it would be possible to state `ensures \initialized(&\result)`, e.g. if we return a `struct` and want to state explicitly that each field has been initialized. Again, the `ensures` of `f` would be translated as `assert E{prms<-args, \result<- retvar}` (or `\result <- lval` for `Post3`).

At a quick glance, it would seem that equating `Pre` with `Pre3` and `Post` with `Post2` or `Post3` would be preferable, but there may be some other subtleties than `\valid` and `\initialized` lying around.

**Comment by AllanBlanchard** [comment]
Related to https://github.com/acsl-language/acsl/issues/49

**Comment by correnson** [comment]
I have the feeling that another program point is important, which is before `lval = retval` and after closing the block that allocated the formals. I have the feeling that the real choice for Post is _before_ affecting the target `lval` which is actually unknown when proving the function in a modular setting.

**Comment by vprevosto** [comment]
But if you do that, you can't "instantiate" the ensures clause by substituting `\result` with `lval`

**Comment by vprevosto** [comment]
that said, I think there's a typo in the code with respect to the position of the `Post*` labels: in the current setting, in both `Post1` and `Post2` everything is allocated, while in `Post3` `retvar` is still allocated. The original code template should read:
```c
// Pre1 
{ 
   rettype retvar;
// Pre2
  { 
     prms = args;
// Pre3
    {
        body;
        retvar = r;
    }
// Post1
  }
// Post2
 lval = retvar;
}
// Post3
```

**Comment by correnson** [comment]
Nice !

If you place Post at `Post3` (in either snippets) instead of `Post2` or `Post2bis`, I'm not sure you can replace `\result` with `lval` in the post-conditions : what if `lval` is aliased in the post ?

Just to illustrate: 

```c
//@ ensures \result == \old(*p); assigns *p;
int f(int *p) { return (*p)++; }

int g(void) {
    int x = 0;
 A:
    x = f(&x);
    //@ check SubstEnsures: x == \at(*(&x),A);
}
```

The assertion which is obtained by substituting `\result` by `x` in the post-condition, simply does not hold :grimacing:

**Comment by vprevosto** [comment]
Indeed, we can't do this substitution. On the other hand, this is strictly a problem of the caller. Hence, I do not understand the issue with `f`. With `main`, on the other hand, we indeed have a problem. But I'm afraid it is in fact deeply ingrained in the C standard, and more precisely 6.5.2.2§10:
> There is a sequence point after the evaluations of the function designator and the actual
arguments but before the actual call. Every evaluation in the calling function (including
other function calls) that is not otherwise specifically sequenced before or after the
execution of the body of the called function is indeterminately sequenced with respect to
the execution of the called function

There's no sequence point in `main` between `A` and the `;` after the call to `f`. It could thus be argued that a compiler smart enough to detect that `f` will return the value contained in `x` could choose to make the assignment in `main` _before_ the call to `f`, potentially optimize it away since it would amount to `x=x`, and only after that perform the side effects of `f` itself, putting `0` into `x`.

**Comment by correnson** [comment]
Yes indeed, there is actually an undefined sequence hidden behind the scene...

**Comment by vprevosto** [comment]
Actually it's not "undefined" (in the dreaded "undefined behavior" :fearful: sense), but "indeterminately sequenced", meaning that after the `;` we can only end up in one of the two situations, either `x == \at(x,A)` or `x==0`.

**Comment by pbaudin** [comment]
In 3 of your previous code schemes, there is the assigment `prms = args;`. But, in order to remove any ambiguity, where do you place the declaration `prmstype prms;` ?

**Comment by vprevosto** [comment]
at the same place (it was meant to represent an initialization rather than a simple assignment).

**Comment by correnson** [comment]
A short example that concretize all the problems to be discussed :

```c
/*@
   requires InValid: \valid(&p);
   requires InInit: \initialized(&p);
   ensures OutValid: \valid(&x);
   ensures OutInit : \initialized(&p);
   ensures RetValid: \valid(\return);
   ensures RetInit: \initialized(\return);
*/
struct S *callee(struct S p) { return &p; }

void caller(void) {
   struct S p, * r ;
   r = callee(p);
   //@ assert WRONG: \valid(p);
}


```

**Comment by vprevosto** [comment]
If we agree on `Post` meaning `Post2` (in the sense of [this comment](https://github.com/acsl-language/acsl/issues/70#issuecomment-771033441)), `OutValid` and `RetValid` do not hold.
