### ISSUE TITLE
Clarification on order of arguments for termination measure

### ISSUE THREAD

**Issue by zilbuz** [acsl-language/acsl#79]
In the termination paragraph (2.5), the order of arguments for the measure is not clear.

The equivalence `R(x, y) <==> x > y && x >= 0` for the integer measure (§2.5.1) uses the first argument `x` as the previous value, but the example `lexico(intpair p1, intpair p2)` in the general measure (§2.5.2) seems to use the second argument `p2` as the previous value as the definition of the predicate is similar to `p2 > p1 && p2 >= 0`.

What is the correct order of arguments?

**Comment by pbaudin** [comment]
Unfortunately, there is a typo in the example.  That is fixed by e0da6be76 commit.
